blog/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name='home'),
    path('about/', views.About.as_view(), name='about'),
    path('acount_mangment/', include('accounts.urls', namespace="acounts")),
    path('blog/', include('blog_app.urls', namespace="blog_app")),
]

blog/blog_app/urls.py
from django.urls import path
from . import views

app_name = "blog_app"

urlpatterns = [
    path('create/', views.create_blog_post.as_view(), name='create'),
    path('view/<int:pk>/', views.view_blog_post.as_view(), name='view'),
    path('all_posts/', views.all_blog_posts.as_view(), name='all'),
    path('delete/<int:id>/', views.delet_blog_post, name='delete'),
]

blog/accounts/models.py
from django.db import models
from django.contrib import auth
from django.utils import timezone

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

blog/blog_app/models.py
from django.db import models
from taggit.managers import TaggableManager

# Create your models here.
class IpModel(models.Model):
    ip = models.CharField(max_length=100)

    def __str__(self):
        return self.ip

class Blog_Post(models.Model):
    slug = models.SlugField(max_length=1000, editable=False, null=True)
    post_title = models.CharField(max_length=100, editable=True, blank=False, null=True)
    blog_content = models.TextField(max_length=10000, blank=False, editable=True, null=True)
    date = models.DateTimeField(blank=False, null=True, auto_now=True, editable=False)
    likes = models.ManyToManyField(IpModel, related_name="post_likes", blank=True)

    def save(self, *args, **kwargs):
        self.slug = self.slug
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("mypage_detail", kwargs={"pk": self.pk})

blog/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

blog/accounts/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("acounts:login")
    template_name = "accounts/signup.html"

blog/blog/views.py
from django.views.generic import TemplateView

class Home(TemplateView):
    template_name = 'index.html'

class About(TemplateView):
    template_name = 'about.html'

blog/blog_app/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from .models import Blog_Post
import logging

User = get_user_model()


class create_blog_post(generic.CreateView):
    model = Blog_Post
    template_name = 'blog_app/creat_post.html'
    fields = ('post_title', 'blog_content')
    success_url = reverse_lazy('blog_app:all')


class view_blog_post(generic.DetailView):
    model = Blog_Post
    template_name = 'blog_app/view_post.html'



def delet_blog_post(request, id):
    blog_post = Blog_Post.objects.get(id=id)
    blog_post.delete()
    return redirect("/")


class all_blog_posts(generic.ListView):
    model = Blog_Post
    template_name = 'blog_app/all_posts.html'
    #slug_url_kwarg = "slug"

blog/accounts/templates/accounts/login.html
{% extends "base.html" %}

{# at the terminal, run pip install django-bootstrap4 #}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h1>Login</h1>
  <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Login</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

blog/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{# at the terminal, run pip install django-bootstrap4 #}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h1>Sign Up</h1>
  <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Sign Up</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

blog/blog_app/templates/blog_app/all_posts.html
{% extends "base.html" %}

{% block content %}
<div class="container">
<h1 id="tittle">Code Wizard Blog Posts</h1>
</div>
<div class="container">
  <ul class="list-group">
    {% for blog_post in object_list  %}
    <a href="{% url 'blog_app:view' blog_post.id %}"><li class="list-group-item">{{blog_post.post_title}}</li></a>
    {% endfor %}
</ul>
</div>
{% endblock %}

blog/blog_app/templates/blog_app/creat_post.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}

  <h1>Create blog poss here</h1>
  <div class="jumbotron">
    <form class="form-horizontal" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="btn btn-success">Submit</button>
     </form>
  </div>
{% endblock %}

blog/blog_app/templates/blog_app/view_post.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <div class="container text">
    <h1>{{blog_post.post_title}}</h1>
  </div>
  <p>{{ blog_post.blog_content|linebreaks  }}</p>
  {% if user.is_authenticated %}
  <a href="{% url 'blog_app:delete' blog_post.id %}"><button type="button" class="btn btn-danger">Delet</button></a>
  {% endif %}
</div>
{% endblock %}

blog/templates/about.html
{% extends "base.html" %}

{% block about_content %}
<div class="page-content jumbotron">
<h1 id='header'>About</h1>
<div class="pargraph">
  <p>Hello world, my name is Ethan(aka The Code Wizard), and this is my blog.
  Before I discuss why I made this blog, I will tell you a little about me. I am a teenage web developer who goes to Robinson secondary school.
  I will be going into my junior year at the time of writing. I have been coding for almost 3 years now, and I am a game dev, full-stack web dev. I can also code in C#, Python, HTML, and CSS.
  Now that you know a little about me, I will tell you why I made this blog. The first reason is to keep me accountable. So I will try to post at least once a week.
  Each post will be an update on a project I am working on. The second reason I made this blog is for it to serve as my personal portfolio. I will also be adding to this blog as I feel like it.
  I hope to add forums and places for fellow devs to share code. I hope you enjoy this blog. </p>
</div>
</div>
{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title>Blog</title>
    <link rel="stylesheet" href={% static "css/master.css" %}>
  </head>
  <body>
    <div class="navbar mynav">
      <div class="container">
        <ul class='nav navbar-nav navbar-left'>
            <li><a href="{% url 'home' %}" class="btn btn-simple button"><h3>Home</h3></a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple"><h3>Logout</h3></a></li>
            <li><a href="{% url 'blog_app:create' %}" class="btn btn-simple"><h3>Create</h3></a></li>
            {% endif %}
            <li><a href="{% url 'blog_app:all' %}" class="btn btn-simple"><h3>Blog Posts</h3></a></li>
            <li><a href="{% url 'about' %}" class="btn btn-simple"><h3>About</h3></a></li>
        </div>
    </div>
  {% block content %}
{% endblock %}
{% block about_content %}
{% endblock %}
  </body>
</html>

blog/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class=".col-md-6"><h1 id="welcom_text">Welcom to my blog</h1></div>
{% endblock %}